language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
daploy:
  provider: pypi
  user: albertomarin-pypi
  password:
    secure: ZW6kvAlNS+krp/x1yvOjAD0NEMa7pCDPFvXhmmDlAAz1W/fUbiUM50z0bTyIuMGgDxP/q83sHW6SCgJ7+mHM4Q4lwqy360mb9BrQ31lw02p5IDJeMr+Me9q0CbIomINUV6Cp/UHjotnAnYh+hFsB1CfP1SeufUfmgJPQ976LfIlTJUWp31YtOWI/6ClkWCX4tPnwD2/95DoSknqvgwTbfVXblIeMvQuu74prITUsXWR5NqCBxLBAqq1c//USG40YFtGHNBWpCCejV+Q+VLv8By7niK8r1BTalKnpl+wlKP6vzBca9BViW6aG9ZVPlgXSHVu8QAP0ezymq5AbTtS+uNh4Q/xGaDm+k4JnVRKCAN2qeOSiY355Vq9ainwMv8FOG1dogvU5b2eJTmSgiWncL5VZgrJ9nZeOVuU49hpFLBm6CK31Q3Mg/d055evyBtLMeBwh8j8mDOkHigMDJMQpHNMratYEHJIphlQdvX8lf5Q7tz2/CS6icTumxInOGVSy2hu436jXXtcT3c63Q6gM0NQIinBvza64xXpdRftGbdWoG+eBcXGmrRGIGd0YH5gJDNIVy/xOwZXW2xSATTBJjfRb3RodCn/5GQYUjanIaG7hSarFuwisLEvkpbIV87J8COFFewTkggYS3Jz40EqV8aOuGvVuKWt3wK2DsGksWV8=
  on:
    tags: true
