language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user:
    secure: TFuyh41Oo1sPEUai77aPc8rWeEN28bPXxmxdzQiskhJPPyVbyaT25bDS2TmatdC/CFif4fao3WoGe/FeEGNj0vDbF+hZ84A5V2d9IVZCM/OSsr1DhczzXallzUw46AmygkwMtJbh38Ex6FbEx7kLYhP6s31Cfu/ru+3tb+iqBT3qU+WH9pRmNtmiUmwqQqwxvBaEJatSLq8Nzd0TQHnTWwGlC03SfHoQxL69MMStCAhIO2OF1EUYN3WzUvvmpAXJQDGHtX5E4DKnC/Y2/hzBpEJ4h8xZb5mUKooESsqJ6v4qKbJgNGylJ9OrCNuQpTw3Ne34Ip2RwtvJy9MVTXNGcVLhk4kXxVznSwRTK5u/ibqBNjYnW+i0Xe0lsYR3QF5+0ef8yjV0y8uLKNW2aqsAuqh5cQWwUreo46bVoEm3xXvlOSdN9/F6Q1dzFw4RdKlK0Nw1zyTKEfQfNURKAZXPewF34RYJf9+EYacUXfx3iUjeYGjy5ax823fKFXGQGAN7CCkjkbMKTY5Svx/F3t+g8n6SgrnaD1xvjsgsYSzmXwDNrMN0HZm3CMQ82wwgO4m4eugL0Pd3Ybma7B7vLq9wUvd93ucl+HV7yGECAOi34AE2csDGbgAQCaZQrbqlNs+kSfie2Kt+traaeNrM6rxGeOuqd3spvSyH0QjFPQhtKWo=
  password:
    secure: HxwGZyLY3He5VGUdqHqplcJMvC8o4+nOyCXq6RvEVT5lcgk7wK+sWsWypB5UJRH/n0Aed2sf6kgUoccwBnZLyErrytsX0DD1MVcu1M1ePF5GnK6cFjTxLk9yMZyqYLJIjvIprsRgLSQLKomcJg5hwVMBgt1fSzq+Rf3cYx8b4ycOts949/2R8JkOJO2A+JLfOxwgHL7fb4BmbzbnFKvIovh9XraLqgdbEnG/lDg7og0VOnViqt20VfflZJ8wb3lNPnazx2bCc8utRRr3EZ0QbUsLe48ji2Ty8XjaQjie1pkAjcX+URNWI5k8x1o8Vx+m9Ulw3Zy6d15313BRhMUHA4LIFU31hDwURaj7cS3FJrrwNj3toOBcl12ISuXEWdbmo8wSnfu1NIPEtEzG7YKoFcmHAYh4MukpC1TCpZKEKTjOsOWMlbkR3LMPVsPXeusV9ZTPdS/oSDpzIirX6fPNMgyy2N0Xp1sMJ0aAiNcMd1PtmZpPcuogKBeXnjE4r+THOAqQrTW5C75XazKw4LgLRlEVLlcbJpHH9oNdhuD6/bMSpRSMlHNykv7PvJSITGfbgxQX4WShQKP1Tf2lxMZu8pj871n6trFjrr/byGiyF282H5Ji3qRGogjk9lDg82fNFriT6L6ckmojZIYp8SPCgym3SzJD/CoJp/BbZ8/PxSI=
  on:
    tags: true
    repo: git-albertomarin/badX12
    python: 3.6
